//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopsDefault.AdminTools.Modules.FilesManager
{


    public partial class main
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl files_manager_ww;
    }
}
